CREATE DATABASE cuentas_michel_db owner postgres;

-- DROP SEQUENCE public.cliente_cliente_id_seq;

CREATE SEQUENCE public.cliente_cliente_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.cuenta_cuenta_id_seq;

CREATE SEQUENCE public.cuenta_cuenta_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.movimiento_movimiento_id_seq;

CREATE SEQUENCE public.movimiento_movimiento_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.persona_persona_id_seq;

CREATE SEQUENCE public.persona_persona_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tipo_cuenta_tipo_cuenta_id_seq;

CREATE SEQUENCE public.tipo_cuenta_tipo_cuenta_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tipo_identificacion_tipo_identificacion_id_seq;

CREATE SEQUENCE public.tipo_identificacion_tipo_identificacion_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;
-- DROP SEQUENCE public.tipo_movimiento_tipo_movimiento_id_seq;

CREATE SEQUENCE public.tipo_movimiento_tipo_movimiento_id_seq
	INCREMENT BY 1
	MINVALUE 1
	MAXVALUE 9223372036854775807
	START 1
	CACHE 1
	NO CYCLE;

-- public.tipo_cuenta definition

-- Drop table

-- DROP TABLE public.tipo_cuenta;

CREATE TABLE public.tipo_cuenta (
	tipo_cuenta_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nombre varchar(1024) NOT NULL,
	CONSTRAINT "PK_tipo_cuenta" PRIMARY KEY (tipo_cuenta_id)
);


-- public.tipo_identificacion definition

-- Drop table

-- DROP TABLE public.tipo_identificacion;

CREATE TABLE public.tipo_identificacion (
	tipo_identificacion_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nombre varchar(1024) NOT NULL,
	CONSTRAINT "PK_tipo_identificacion" PRIMARY KEY (tipo_identificacion_id)
);


-- public.tipo_movimiento definition

-- Drop table

-- DROP TABLE public.tipo_movimiento;

CREATE TABLE public.tipo_movimiento (
	tipo_movimiento_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nombre varchar(1024) NOT NULL,
	CONSTRAINT "PK_tipo_movimiento" PRIMARY KEY (tipo_movimiento_id)
);


-- public.persona definition

-- Drop table

-- DROP TABLE public.persona;

CREATE TABLE public.persona (
	persona_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	nombre varchar(1024) NOT NULL,
	genero varchar(1024) NOT NULL,
	edad int4 NOT NULL,
	tipo_identificacion_id int8 NOT NULL,
	identificacion varchar(1024) NOT NULL,
	direccion varchar(1024) NOT NULL,
	telefono varchar(1024) NOT NULL,
	CONSTRAINT "PK_persona" PRIMARY KEY (persona_id),
	CONSTRAINT "FK_persona_tipo_identificacion_tipo_identificacion_id" FOREIGN KEY (tipo_identificacion_id) REFERENCES public.tipo_identificacion(tipo_identificacion_id) ON DELETE CASCADE
);
CREATE INDEX "IX_persona_tipo_identificacion_id" ON public.persona USING btree (tipo_identificacion_id);


-- public.cliente definition

-- Drop table

-- DROP TABLE public.cliente;

CREATE TABLE public.cliente (
	cliente_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	usuario text NOT NULL,
	"password" text NOT NULL,
	estado bool NULL,
	persona_id int8 NOT NULL,
	CONSTRAINT "PK_cliente" PRIMARY KEY (cliente_id),
	CONSTRAINT "FK_cliente_persona_persona_id" FOREIGN KEY (persona_id) REFERENCES public.persona(persona_id) ON DELETE CASCADE
);
CREATE UNIQUE INDEX "IX_cliente_persona_id" ON public.cliente USING btree (persona_id);


-- public.cuenta definition

-- Drop table

-- DROP TABLE public.cuenta;

CREATE TABLE public.cuenta (
	cuenta_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	tipo_cuenta_id int8 NOT NULL,
	numero_cuenta varchar(1024) NOT NULL,
	saldo int4 NOT NULL,
	estado bool NOT NULL,
	cliente_id int8 NOT NULL,
	CONSTRAINT "PK_cuenta" PRIMARY KEY (cuenta_id),
	CONSTRAINT "FK_cuenta_cliente_cliente_id" FOREIGN KEY (cliente_id) REFERENCES public.cliente(cliente_id) ON DELETE CASCADE,
	CONSTRAINT "FK_cuenta_tipo_cuenta_tipo_cuenta_id" FOREIGN KEY (tipo_cuenta_id) REFERENCES public.tipo_cuenta(tipo_cuenta_id) ON DELETE CASCADE
);
CREATE INDEX "IX_cuenta_cliente_id" ON public.cuenta USING btree (cliente_id);
CREATE INDEX "IX_cuenta_tipo_cuenta_id" ON public.cuenta USING btree (tipo_cuenta_id);


-- public.movimiento definition

-- Drop table

-- DROP TABLE public.movimiento;

CREATE TABLE public.movimiento (
	movimiento_id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	tipo_movimiento_id int8 NOT NULL,
	fecha date NOT NULL,
	saldo_inicial int4 NOT NULL,
	valor int4 NOT NULL,
	saldo int4 NOT NULL,
	cuenta_id int8 NOT NULL,
	CONSTRAINT "PK_movimiento" PRIMARY KEY (movimiento_id),
	CONSTRAINT "FK_movimiento_cuenta_cuenta_id" FOREIGN KEY (cuenta_id) REFERENCES public.cuenta(cuenta_id) ON DELETE CASCADE,
	CONSTRAINT "FK_movimiento_tipo_movimiento_tipo_movimiento_id" FOREIGN KEY (tipo_movimiento_id) REFERENCES public.tipo_movimiento(tipo_movimiento_id) ON DELETE CASCADE
);
CREATE INDEX "IX_movimiento_cuenta_id" ON public.movimiento USING btree (cuenta_id);
CREATE INDEX "IX_movimiento_tipo_movimiento_id" ON public.movimiento USING btree (tipo_movimiento_id);

-- Inserts public.tipo_cuenta
INSERT INTO public.tipo_cuenta (nombre) VALUES('Ahorros');
INSERT INTO public.tipo_cuenta (nombre) VALUES('Corriente');

-- Inserts public.tipo_identificacion
INSERT INTO public.tipo_identificacion (nombre) VALUES('Cédula ciudadanía');
INSERT INTO public.tipo_identificacion (nombre) VALUES('Tarjeta de identidad');
INSERT INTO public.tipo_identificacion (nombre) VALUES('Registro civil');

-- Inserts public.tipo_movimiento
INSERT INTO public.tipo_movimiento (nombre) VALUES('Deposito');
INSERT INTO public.tipo_movimiento (nombre) VALUES('Retiro');